name: intuitive_bayes
channels:
  - conda-forge
dependencies:
  - jupyterlab=4.1.1
  - matplotlib=3.8.3
  - numpy=1.26.4
  - pandas=2.2.0
  - pyarrow=15.0.0
  - pymc=5.10.4
  - python=3.11
  - python-graphviz=0.20
  - scipy=1.12.0
  - seaborn=0.13.2
